# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'infiniteProducts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for infiniteProducts
  pod 'Siesta', '~> 1.0'
  pod "Unbox", '~> 2.5.0'

  target 'infiniteProductsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
